// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TileMapTx struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TileMapTx) Reset()         { *m = TileMapTx{} }
func (m *TileMapTx) String() string { return proto.CompactTextString(m) }
func (*TileMapTx) ProtoMessage()    {}
func (*TileMapTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *TileMapTx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TileMapTx.Unmarshal(m, b)
}
func (m *TileMapTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TileMapTx.Marshal(b, m, deterministic)
}
func (m *TileMapTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TileMapTx.Merge(m, src)
}
func (m *TileMapTx) XXX_Size() int {
	return xxx_messageInfo_TileMapTx.Size(m)
}
func (m *TileMapTx) XXX_DiscardUnknown() {
	xxx_messageInfo_TileMapTx.DiscardUnknown(m)
}

var xxx_messageInfo_TileMapTx proto.InternalMessageInfo

func (m *TileMapTx) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type TileMapState struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TileMapState) Reset()         { *m = TileMapState{} }
func (m *TileMapState) String() string { return proto.CompactTextString(m) }
func (*TileMapState) ProtoMessage()    {}
func (*TileMapState) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *TileMapState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TileMapState.Unmarshal(m, b)
}
func (m *TileMapState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TileMapState.Marshal(b, m, deterministic)
}
func (m *TileMapState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TileMapState.Merge(m, src)
}
func (m *TileMapState) XXX_Size() int {
	return xxx_messageInfo_TileMapState.Size(m)
}
func (m *TileMapState) XXX_DiscardUnknown() {
	xxx_messageInfo_TileMapState.DiscardUnknown(m)
}

var xxx_messageInfo_TileMapState proto.InternalMessageInfo

func (m *TileMapState) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type PixelMaps struct {
	LinesArray           []*PixelMaps_TileMapLine `protobuf:"bytes,1,rep,name=linesArray,proto3" json:"linesArray,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *PixelMaps) Reset()         { *m = PixelMaps{} }
func (m *PixelMaps) String() string { return proto.CompactTextString(m) }
func (*PixelMaps) ProtoMessage()    {}
func (*PixelMaps) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{2}
}

func (m *PixelMaps) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PixelMaps.Unmarshal(m, b)
}
func (m *PixelMaps) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PixelMaps.Marshal(b, m, deterministic)
}
func (m *PixelMaps) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PixelMaps.Merge(m, src)
}
func (m *PixelMaps) XXX_Size() int {
	return xxx_messageInfo_PixelMaps.Size(m)
}
func (m *PixelMaps) XXX_DiscardUnknown() {
	xxx_messageInfo_PixelMaps.DiscardUnknown(m)
}

var xxx_messageInfo_PixelMaps proto.InternalMessageInfo

func (m *PixelMaps) GetLinesArray() []*PixelMaps_TileMapLine {
	if m != nil {
		return m.LinesArray
	}
	return nil
}

type PixelMaps_TileMapLine struct {
	Color                string   `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Startx               float32  `protobuf:"fixed32,3,opt,name=startx,proto3" json:"startx,omitempty"`
	Starty               float32  `protobuf:"fixed32,4,opt,name=starty,proto3" json:"starty,omitempty"`
	Endx                 float32  `protobuf:"fixed32,5,opt,name=endx,proto3" json:"endx,omitempty"`
	Endy                 float32  `protobuf:"fixed32,6,opt,name=endy,proto3" json:"endy,omitempty"`
	Pixels               []int32  `protobuf:"varint,7,rep,packed,name=pixels,proto3" json:"pixels,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PixelMaps_TileMapLine) Reset()         { *m = PixelMaps_TileMapLine{} }
func (m *PixelMaps_TileMapLine) String() string { return proto.CompactTextString(m) }
func (*PixelMaps_TileMapLine) ProtoMessage()    {}
func (*PixelMaps_TileMapLine) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{2, 0}
}

func (m *PixelMaps_TileMapLine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PixelMaps_TileMapLine.Unmarshal(m, b)
}
func (m *PixelMaps_TileMapLine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PixelMaps_TileMapLine.Marshal(b, m, deterministic)
}
func (m *PixelMaps_TileMapLine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PixelMaps_TileMapLine.Merge(m, src)
}
func (m *PixelMaps_TileMapLine) XXX_Size() int {
	return xxx_messageInfo_PixelMaps_TileMapLine.Size(m)
}
func (m *PixelMaps_TileMapLine) XXX_DiscardUnknown() {
	xxx_messageInfo_PixelMaps_TileMapLine.DiscardUnknown(m)
}

var xxx_messageInfo_PixelMaps_TileMapLine proto.InternalMessageInfo

func (m *PixelMaps_TileMapLine) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *PixelMaps_TileMapLine) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *PixelMaps_TileMapLine) GetStartx() float32 {
	if m != nil {
		return m.Startx
	}
	return 0
}

func (m *PixelMaps_TileMapLine) GetStarty() float32 {
	if m != nil {
		return m.Starty
	}
	return 0
}

func (m *PixelMaps_TileMapLine) GetEndx() float32 {
	if m != nil {
		return m.Endx
	}
	return 0
}

func (m *PixelMaps_TileMapLine) GetEndy() float32 {
	if m != nil {
		return m.Endy
	}
	return 0
}

func (m *PixelMaps_TileMapLine) GetPixels() []int32 {
	if m != nil {
		return m.Pixels
	}
	return nil
}

func init() {
	proto.RegisterType((*TileMapTx)(nil), "TileMapTx")
	proto.RegisterType((*TileMapState)(nil), "TileMapState")
	proto.RegisterType((*PixelMaps)(nil), "PixelMaps")
	proto.RegisterType((*PixelMaps_TileMapLine)(nil), "PixelMaps.TileMapLine")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0xc9, 0x76, 0x5b, 0xe9, 0xd4, 0x53, 0x90, 0x65, 0xf0, 0x62, 0xe8, 0x29, 0xa7, 0x1e,
	0x14, 0xbc, 0x7b, 0x77, 0x41, 0xe2, 0xbe, 0x40, 0x74, 0xe7, 0x10, 0x28, 0x6d, 0x48, 0x72, 0x48,
	0x7c, 0x21, 0x9f, 0xce, 0x77, 0x90, 0xc4, 0x50, 0x7a, 0xf0, 0xf6, 0xff, 0xdf, 0xfc, 0x99, 0x3f,
	0x0c, 0x0c, 0x21, 0x59, 0xf2, 0x93, 0x75, 0x6b, 0x58, 0xc7, 0x07, 0xe8, 0x2f, 0x66, 0xa6, 0xb3,
	0xb6, 0x97, 0xc8, 0x39, 0x1c, 0xaf, 0x3a, 0x68, 0x64, 0x82, 0xc9, 0x5e, 0x15, 0x3d, 0x8e, 0x70,
	0x5b, 0x03, 0xef, 0x41, 0x07, 0xfa, 0x37, 0xf3, 0xc3, 0xa0, 0x7f, 0x33, 0x91, 0xe6, 0xb3, 0xb6,
	0x9e, 0x3f, 0x03, 0xcc, 0x66, 0x21, 0xff, 0xe2, 0x9c, 0x4e, 0xc8, 0x44, 0x23, 0x87, 0xc7, 0xd3,
	0xb4, 0xcd, 0xa7, 0xba, 0xee, 0xd5, 0x2c, 0xa4, 0x76, 0xc9, 0xfb, 0x6f, 0x06, 0xc3, 0x6e, 0xc6,
	0xef, 0xa0, 0xfd, 0x5c, 0xe7, 0xd5, 0xd5, 0xaa, 0x3f, 0x93, 0xfb, 0xbd, 0xf9, 0x22, 0x3c, 0x08,
	0x26, 0x1b, 0x55, 0x34, 0x3f, 0x41, 0xe7, 0x83, 0x76, 0x21, 0x62, 0x23, 0x98, 0x3c, 0xa8, 0xea,
	0x36, 0x9e, 0xf0, 0xb8, 0xe3, 0x29, 0xef, 0xa0, 0xe5, 0x1a, 0xb1, 0x2d, 0xb4, 0xe8, 0xca, 0x12,
	0x76, 0x1b, 0x4b, 0xf9, 0xbd, 0xcd, 0xdf, 0xf6, 0x78, 0x23, 0x1a, 0xd9, 0xaa, 0xea, 0x3e, 0xba,
	0x72, 0xbb, 0xa7, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf9, 0x26, 0x63, 0xa4, 0x4a, 0x01, 0x00,
	0x00,
}
